---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

# If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS: 
  [
    ACTION_ACTIONLINT,
    # Maybe C CPP lint enable later.
    # https://megalinter.io/7.13.0/descriptors/c_cpplint/
    # C_CPPLINT,
    # Maybe CPP lint enable later.
    # https://megalinter.io/latest/descriptors/cpp_cpplint/
    # CPP_CPPLINT,
    EDITORCONFIG_EDITORCONFIG_CHECKER,
    JSON_JSONLINT,
    JSON_V8R,
    MARKDOWN_MARKDOWNLINT,
    REPOSITORY_DUSTILOCK,
    REPOSITORY_GIT_DIFF,
    REPOSITORY_GRYPE,
    REPOSITORY_SECRETLINT,
    REPOSITORY_SYFT,
    REPOSITORY_TRIVY_SBOM,
    REPOSITORY_TRUFFLEHOG,
    YAML_V8R,
    YAML_YAMLLINT,
  ]
DISABLE:
  - COPYPASTE # Disable checks of excessive copy-pastes
  - SPELL # Disable checks of spelling mistakes

DISABLE_LINTERS:
  [
    C_CLANG_FORMAT,
    CPP_CLANG_FORMAT,
    CSS_STYLELINT,
    HTML_HTMLHINT,
    JAVASCRIPT_STANDARD,
    JSON_PRETTIER,
    MARKDOWN_MARKDOWN_LINK_CHECK,
    MARKDOWN_MARKDOWN_TABLE_FORMATTER,
    PROTOBUF_PROTOLINT,
    REPOSITORY_CHECKOV,
    REPOSITORY_DEVSKIM,
    REPOSITORY_GITLEAKS,
    REPOSITORY_KICS,
    SQL_TSQLLINT,
    TYPESCRIPT_STANDARD,
    YAML_PRETTIER,
  ]
DISABLE_ERRORS_LINTERS: [ACTION_ACTIONLINT, REPOSITORY_GRYPE, REPOSITORY_TRIVY, REPOSITORY_TRUFFLEHOG]
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
# Exclude certain files from linting
# yamllint disable-line rule:line-length
FILTER_REGEX_EXCLUDE: "(lib/.*)"
# Use our ESLint rules file
TSX_ESLINT_CONFIG_FILE: www/.eslintrc.yml
