---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default

ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  [
    ACTION_ACTIONLINT,
    EDITORCONFIG_EDITORCONFIG_CHECKER,
    HTML_HTMLHINT,
    JSON_JSONLINT,
    JSON_V8R,
    REPOSITORY_DUSTILOCK,
    YAML_YAMLLINT,
  ]
DISABLE:
  - COPYPASTE # Disable checks of excessive copy-pastes
  - SPELL # Disable checks of spelling mistakes
# Disable the DevSkim linter for now because it is raising false positives
# and there is not a way to specify for the linter to ignore certain lines or certain files: REPOSITORY_DEVSKIM
# https://github.com/microsoft/DevSkim
DISABLE_LINTERS:
  [
    # TODO: disabling C CPP lint for now, but maybe enable it later.
    # https://megalinter.io/7.13.0/descriptors/c_cpplint/
    C_CPPLINT,
    C_CLANG_FORMAT,
    CPP_CLANG_FORMAT,
    # TODO: disabling CPP lint for now, but maybe enable it later.
    # https://megalinter.io/latest/descriptors/cpp_cpplint/
    CPP_CPPLINT,
    CSS_STYLELINT,
    JAVASCRIPT_STANDARD,
    MARKDOWN_MARKDOWN_LINK_CHECK,
    MARKDOWN_MARKDOWN_TABLE_FORMATTER,
    REPOSITORY_DEVSKIM,
    REPOSITORY_GITLEAKS,
    SQL_TSQLLINT,
    TYPESCRIPT_STANDARD,
  ]
DISABLE_ERRORS_LINTERS: [REPOSITORY_GRYPE, REPOSITORY_TRIVY, REPOSITORY_TRUFFLEHOG]
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
# Exclude certain files from linting
# yamllint disable-line rule:line-length
FILTER_REGEX_EXCLUDE: "(lib/.*)"
# Use our ESLint rules file
TSX_ESLINT_CONFIG_FILE: www/.eslintrc.yml
